// <auto-generated />
using MVC_Inventory.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_Inventory.Migrations
{
    [DbContext(typeof(InventoryContext))]
    partial class InventoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ProductInformation.Models.Product", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int(10)");

                    b.Property<string>("Discontinued")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)")
                        .HasAnnotation("MySql:CharSet", "utf8mb4")
                        .HasAnnotation("MySql:Collation", "utf8mb4_general_ci");

                    b.Property<int>("Quantity")
                        .HasColumnType("int(10)");

                    b.HasKey("ID");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            ID = -1,
                            Discontinued = "1",
                            Name = "iPhone",
                            Quantity = 12
                        },
                        new
                        {
                            ID = -2,
                            Discontinued = "1",
                            Name = "iPad",
                            Quantity = 2
                        },
                        new
                        {
                            ID = -3,
                            Discontinued = "1",
                            Name = "iMac",
                            Quantity = 12
                        },
                        new
                        {
                            ID = -4,
                            Discontinued = "0",
                            Name = "iPod",
                            Quantity = 12
                        },
                        new
                        {
                            ID = -5,
                            Discontinued = "1",
                            Name = "Apple Watch",
                            Quantity = 12
                        },
                        new
                        {
                            ID = -6,
                            Discontinued = "1",
                            Name = "Apple Home",
                            Quantity = 12
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
